version: '3.4'

services:

  hn_talentmatch.server:
    image: ${DOCKER_REGISTRY-}hntalentmatchserver
    build:
      context: .
      dockerfile: HN_TalentMatch.Server/Dockerfile
    depends_on:
      - postgres_db
    ports:
      - 5128:80
    restart: always
  
  hn_talentmatch.client:
    image: node:alpine
    build:
       context: .
       dockerfile: HN_TalentMatch.Client/Dockerfile
    container_name: vite_docker
    entrypoint: /bin/sh
    working_dir: /app
    volumes: 
        - ./hn_talentmatch.client:/app
    tty: true
    ports:
      - 5173:5173
    depends_on:
      - hn_talentmatch.server
    restart: always
  
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwertyuiop
      POSTGRES_DB: hn_talentmatch_dev
      PGDATA: /var/lib/postgresql/data

    ports:
      - "5434:5434"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: -p 5434
    restart: always

volumes:
  postgres-data: